name: Informe Automático Avícola

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar a la hora exacta, cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RETENTION_DAYS: 1

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar análisis
        env:
          AIO_USERNAME: ${{ secrets.AIO_USERNAME }}
          AIO_KEY: ${{ secrets.AIO_KEY }}
        run: python main.py

      - name: Preparar carpeta de publicación
        run: |
          mkdir -p public
          cp informe.html public/
          cp clusters.png public/
          cp heatmap.png public/
          cp tendencia_1.png public/
          cp tendencia_2.png public/

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true  # 🔥 PUBLICACIÓN LIMPIA: elimina todo lo anterior
